name: fire
channels:
  - gurobi
  - defaults
  - conda-forge
dependencies:
  - python=3.10.6
  - pip=22.3.1
  - gurobi=10.0.3
  - pip:
    - networkx==2.8.4
    - numpy==1.26.4
    - pandas==2.2.2
    - scipy==1.10.1
    - matplotlib==3.9.0
    - noise==1.2.2
